runtime: python27
api_version: 1
threadsafe: true


# [START handlers]
handlers:
- url: /static
  static_dir: static
  application_readable: true
- url: /.*
  script: app.app

# [END handlers]

env_variables:
  TWILIO_ACCOUNT_SID: 'ACe88621c6ec7c3b0e89dc7d58516758f3'
  TWILIO_API_KEY: 'SK9650c4d120e826dfd6cc2900d5b95d24'
  TWILIO_API_SECRET: '9ehpuUmpAR7dITTLnwFrShUrWsQmknyX'
  # Required for Chat
  TWILIO_CHAT_SERVICE_SID: 'IS01a7b217a47d4dae950e6b4f5f1601c0'

  TWILIO_NOTIFICATION_SERVICE_SID: ''
  TWILIO_SYNC_SERVICE_SID: ''
  