runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.app
# [END handlers]
env_variables:
  GOOGLE_CLIENT_ID: '119855237642-p3ckimhcgmb2ljnigcegvrh1v43eb1ba.apps.googleusercontent.com'
  GOOGLE_CLIENT_SECRET: 'eVGXh0tufuuqgY5YK0zz0Sck'
  REDIRECT_URI: '/oauth2callback'