runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 2

# [START handlers]
handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.app
# [END handlers]
env_variables:
  #Google SignIn
  GOOGLE_CLIENT_ID: '119855237642-p3ckimhcgmb2ljnigcegvrh1v43eb1ba.apps.googleusercontent.com'
  GOOGLE_CLIENT_SECRET: 'eVGXh0tufuuqgY5YK0zz0Sck'
  REDIRECT_URI: '/oauth2callback'
  SECRET_KEY: 'development key'
  #MongoDB URI
  MONGODB_URI: 'mongodb://user:Sanbao941104@socialfamily-shard-00-00-03pay.mongodb.net:27017,socialfamily-shard-00-01-03pay.mongodb.net:27017,socialfamily-shard-00-02-03pay.mongodb.net:27017/test?ssl=true&replicaSet=SocialFamily-shard-0&authSource=admin'
  #TWILIO 
  TWILIO_ACCOUNT_SID: 'AC1a56fb7a7e97f28e9ba30f2b23ed7396'
  TWILIO_API_KEY: 'SKbfb9ef9ab406f0ae27689bece5f40f25'
  TWILIO_API_SECRET: 'azX2cxpwWhsRw23DQgiPuWTzm2dLh5FY'
  # Required for Chat
  TWILIO_CHAT_SERVICE_SID: 'ISbdd6858ca5aa4157886e638f45a7e361'
  TWILIO_SYNC_SERVICE_SID: 'IS00903250036e25a9bd6956e078795864'